coursera/dataduct

- bin/dataduct
Fragmented dataduct into multiple subparsers
> Fragmented dataduct into multiple subparsers

- bin/dataduct
- dataduct/etl/etl_actions.py
Add 'activites-only' filter for etl visualization
> Add 'activites-only' filter for etl visualization

- dataduct/database/parsers/create_table.py
- dataduct/database/parsers/create_view.py
- dataduct/database/parsers/tests/test_create_table.py
- dataduct/database/parsers/tests/test_create_view.py
- dataduct/database/sql/sql_script.py
- dataduct/database/table.py
- dataduct/database/view.py
- dataduct/steps/qa_transform.py
Add one test for table and view parser
> Fix for table parser in table attributes

- bin/dataduct
- dataduct/config/logger_config.py
- dataduct/database/database.py
- dataduct/database/sql/sql_script.py
- dataduct/database/table.py
- dataduct/etl/etl_actions.py
- dataduct/utils/exceptions.py
- examples/tables/categories.sql
- examples/tables/customers.sql
- examples/tables/employees.sql
- examples/tables/order_details.sql
- examples/tables/orders.sql
- examples/tables/products.sql
- examples/tables/shippers.sql
- examples/tables/suppliers.sql
Add database actions and visualization
> Add database actions and visualization

- bin/dataduct
- dataduct/database/database.py
- dataduct/database/parsers/select_query.py
- dataduct/database/parsers/tests/test_create_table.py
- dataduct/database/select_statement.py
- dataduct/database/sql/tests/test_sql_script.py
- dataduct/database/table.py
- dataduct/database/tests/test_database.py
- dataduct/database/view.py
- dataduct/etl/tests/test_definition_parser.py
- dataduct/tests/test_import.py
- requirements.txt
Most unittests are for database.py
Added testfixtures framework to mock files
> Add many unit tests, fix some bugs

- .travis.yml
- README.rst
- dataduct/qa/check.py
> Travis Integration

- dataduct/database/database.py
- dataduct/database/history_table.py
- dataduct/database/relation.py
- dataduct/database/select_statement.py
- dataduct/database/table.py
- dataduct/database/tests/test_database.py
- dataduct/database/tests/test_history_table.py
Added History Table Class, bug fixes
> Added History Table Class, bug fixes

- dataduct/database/tests/test_history_table.py
- dataduct/etl/etl_pipeline.py
- dataduct/qa/check.py
- dataduct/steps/__init__.py
- dataduct/steps/column_check.py
- dataduct/steps/scripts/column_check_test.py
- dataduct/steps/scripts/primary_key_test.py
- dataduct/utils/constants.py
- examples/example_column_check.yaml
- examples/tables/dev.test_table2.sql
> Add Column Check step

- .gitignore
- dataduct/pipeline/data_pipeline.py
- dataduct/pipeline/utils.py
```
etl:
REGION: us-west-2
```
> Supporting region property

- dataduct/steps/etl_step.py
- dataduct/steps/transform.py
This output_path parameter in transform step does not work. So fixed.
> Fixed output_path parameter in transform step

- dataduct/qa/count_check.py
- dataduct/steps/count_check.py
> Change to count check

- dataduct/etl/etl_actions.py
- dataduct/utils/slack_hook.py
Config file:
```
etl:
slack:
api_token:
channel_name:
[bot_username:]
```
`bot_username` is optional, defaults to 'Dataduct'
> Hooked up slack integration

- dataduct/database/parsers/utils.py
- dataduct/database/relation.py
- dataduct/etl/tests/test_etl_actions.py
- dataduct/etl/tests/test_etl_pipeline.py
- dataduct/steps/scripts/column_check_test.py
- dataduct/steps/scripts/create_load_redshift_runner.py
- dataduct/steps/transform.py
> Bug fixes for count check

- .travis.yml
5 minutes to 3 minutes of build time!
> Implement container builds

- bin/dataduct
- dataduct/etl/etl_actions.py
- dataduct/etl/etl_pipeline.py
- dataduct/etl/tests/test_etl_actions.py
- dataduct/pipeline/data_pipeline.py
- dataduct/pipeline/schedule.py
> Add resource tagging to pipelines

- dataduct/etl/etl_pipeline.py
> Fixing the log uri

- dataduct/etl/etl_pipeline.py
- dataduct/steps/count_check.py
- dataduct/steps/transform.py
> Bug squashing

- dataduct/database/parsers/utils.py
> Add more characters to parser

- dataduct/etl/etl_pipeline.py
- dataduct/etl/tests/test_etl_pipeline.py
- examples/example_transform.yaml
> Ec2 inputs should all be modifiable

- bin/dataduct
- dataduct/config/config_actions.py
- dataduct/etl/etl_actions.py
@tpcstld this is an implementation with individual parsers for each option to make them secure
```
dataduct [-h]
dataduct pipeline [-h]
dataduct pipeline create [-m mode] [-h] [-d delay] [-f force] load_definitions
dataduct pipeline validate [-m mode] [-h] [-d delay] [-f force] load_definitions
dataduct pipeline activate [-m mode] [-h] [-d delay] [-f force] load_definitions
dataduct pipeline visualize [-m mode] [-h] [--activities_only] filename load_definitions
dataduct database [-h]
dataduct database create [-m mode] [-h] table_definitions
dataduct database grant [-m mode] [-h] table_definitions
dataduct database drop [-m mode] [-h] table_definitions
dataduct database recreate [-m mode] [-h] table_definitions
dataduct database visualize [-m mode] [-h] filename table_definitions
dataduct …
```
> CLI update for parameter regulation

- bin/dataduct
- dataduct/database/database.py
- dataduct/database/parsers/create_table.py
- dataduct/database/parsers/select_query.py
- dataduct/database/parsers/utils.py
- dataduct/etl/etl_pipeline.py
- dataduct/etl/tests/test_etl_pipeline.py
- examples/example_transform.yaml
- setup.py
- Autocomplete in dataduct -> The installation has one more step which I would add to the documentation
- CLI help messages and flow changed to make it more intutive
- Comments added to the parser trickiness
> Autocomplete and CLI help update

- dataduct/steps/scripts/column_check_test.py
> Encode strings in ColumnCheck in utf-8

- dataduct/steps/upsert.py
> Put the script filename through parse_path first

- dataduct/pipeline/utils.py
> Actually set the variable to be a connection

- dataduct/steps/pipeline_dependencies.py
> name prefix and dependency_override

- bin/dataduct
- dataduct/database/parsers/select_query.py
- dataduct/database/parsers/tests/test_select_query.py
- dataduct/database/parsers/utils.py
- dataduct/etl/etl_pipeline.py
- dataduct/etl/tests/test_etl_pipeline.py
- dataduct/pipeline/default_object.py
- dataduct/pipeline/schedule.py
- dataduct/tests/test_import.py
- requirements.txt
- setup.py
> Backfill + with query + frequency override

- dataduct/steps/scripts/create_load_redshift_runner.py
> Fix double quotes issue with replace_invalid_char

- dataduct/etl/etl_actions.py
> Fixed monitoring pipeline url when the region used

- dataduct/steps/qa_transform.py
- dataduct/steps/transform.py
@tpcstld this removes the redundant S3 nodes that were being created by QA steps. PTAL
> QA steps don't create an output node

- dataduct/database/parsers/utils.py
> INT keyword

- dataduct/config/example_config
- dataduct/config/logger_config.py
- dataduct/steps/extract_s3.py
- dataduct/steps/transform.py
- dataduct/utils/helpers.py
> path fixes

- dataduct/steps/sql_command.py
> Do not check the type of sqlscript if it is None

- dataduct/config/logger_config.py
> Change placement of expanduser so that you can write '~' in config file

- dataduct/database/table.py
- dataduct/database/view.py
- dataduct/steps/create_load_redshift.py
- dataduct/steps/create_update_sql.py
- dataduct/steps/scripts/create_load_redshift_runner.py
- dataduct/steps/scripts/sql_runner.py
- dataduct/steps/upsert.py
- dataduct/utils/constants.py
> Move upsert to shell command activity

- dataduct/steps/create_update_sql.py
@sb2nov PTAL
I should/will add some unit tests for these things...
> Add script_arguments for create_update_sql

- dataduct/etl/etl_pipeline.py
- dataduct/qa/check.py
- dataduct/steps/create_update_sql.py
- dataduct/steps/scripts/sql_runner.py
- dataduct/utils/constants.py
- examples/example_create_update_sql.yaml
- examples/example_primary_key_check.yaml
@tpcstld PTAL
The SQL queries can now be written as `select * from xzy where x=%s` and it should work fine. This provides similar functionality as sql command but we don't have to create tables anymore.
> SQL options

- bin/dataduct
> Only convert the timedelta once, instead of for every pipeline

- dataduct/steps/create_update_sql.py
- dataduct/steps/scripts/sql_runner.py
> Only send args if args actually exist

- CHANGES.md
- dataduct/config/credentials.py
- dataduct/pipeline/utils.py
- docs/conf.py
- docs/config.rst
- docs/creating_an_etl.rst
- docs/dataduct.config.rst
- docs/dataduct.config.tests.rst
- docs/dataduct.data_access.rst
- docs/dataduct.database.parsers.rst
- docs/dataduct.database.parsers.tests.rst
- docs/dataduct.database.rst
- docs/dataduct.database.sql.rst
- docs/dataduct.database.sql.tests.rst
- docs/dataduct.database.tests.rst
- docs/dataduct.etl.rst
- docs/dataduct.etl.tests.rst
- docs/dataduct.pipeline.rst
- docs/dataduct.qa.rst
- docs/dataduct.rst
- docs/dataduct.steps.rst
- docs/dataduct.tests.rst
- docs/dataduct.utils.rst
- docs/etl_pipeline.rst
- docs/index.rst
- docs/input_output.rst
- docs/installation.rst
- docs/introduction.rst
- docs/modules.rst
- docs/steps.rst
> Documentation

- dataduct/database/__init__.py
> Add column to init

- dataduct/database/table.py
> Add ability for Table to handle strings

- dataduct/steps/transform.py
> Convert script_arguments to a list if it is None in transform step

- dataduct/s3/utils.py
- dataduct/utils/cli.py
- dataduct/utils/helpers.py
> download from s3

- dataduct/steps/scripts/create_load_redshift_runner.py
- dataduct/utils/helpers.py
- dataduct/utils/tests/test_helpers.py
> Refactor the credential serialization so it's testable and reuseable

- docs/config.rst
- docs/hooks.rst
- docs/index.rst
> Add docs for hooks

- dataduct/etl/etl_actions.py
- dataduct/utils/helpers.py
- dataduct/utils/tests/test_helpers.py
> Refactor getting the url to be in a helper method instead

- dataduct/config/config.py
- dataduct/config/tests/test_config.py
@sb2nov PTAL
Will investigate how to test the singleton :P
> Add tests for config, everything but the config itself

- dataduct/database/database.py
> Add a tables_to_show filter to the database visualization

- dataduct/s3/utils.py
> Don't append another '/' to an S3Directory

- dataduct/steps/transform.py
- docs/steps.rst
@sb2nov PTAL
Also I added some documentation about the resource_type argument.
> Change script arguments to use S3_BASE_PATH too

- docs/creating_an_etl.rst
> Add docs about the bootstrap string

- dataduct/utils/tests/test_hook.py
> Add tests for hooks

- dataduct/database/parsers/tests/test_get_column_parser.py
- dataduct/database/parsers/utils.py
@sb2nov Here's a separate PR with the tests for the column parser.
> Add tests for column parser

- dataduct/config/tests/test_config.py
- dataduct/config/tests/test_config_actions.py
- dataduct/data_access/tests/test_connection.py
- dataduct/database/column.py
- dataduct/database/tests/test_column.py
> Add more tests for column and config

- bin/dataduct
- dataduct/database/parsers/create_table.py
- dataduct/database/table.py
- dataduct/pipeline/schedule.py
> Fix the frequency start time in weekly case

- dataduct/config/logger_config.py
- docs/config.rst
* Correct config path in config doc
> * Raise exception when logging is missing in config

- dataduct/data_access/connection.py
- dataduct/steps/scripts/sql_runner.py
Reviewers: sbajaj
CC:
Test Plan: no test yet, going to test it tomorrow before the merge
Auditors:
> Fix autocommit

- dataduct/data_access/connection.py
Reviewers: sbajaj
CC:
Test Plan:
Auditors:
> Fix wrong usage of connection

- docs/config.rst
Config should no longer exist since the implementation was removed.
> Slack config is no longer being used

- dataduct/etl/etl_pipeline.py
- dataduct/pipeline/emr_resource.py
- dataduct/pipeline/pipeline_object.py
> Add default bootstrap

- dataduct/etl/etl_actions.py
- dataduct/etl/etl_pipeline.py
- dataduct/pipeline/default_object.py
- dataduct/steps/etl_step.py
> Add teardown action for sns alerts

- dataduct/steps/scripts/pipeline_dependency_check.py
> Making pipeline dependency error more useful.

- dataduct/steps/reload.py
to surface data quality issues.
> make reload not dedup on primary key by default

- dataduct/steps/reload.py
> Obey YAML file in reload pk check

- dataduct/etl/etl_pipeline.py
> Fix data directory for high freq load

- dataduct/database/parsers/utils.py
Make back tick part of the db name for escaping
> Escape char ` part of dependencies

- dataduct/__init__.py
> Bump to 0.3

- dataduct/steps/scripts/create_load_redshift_runner.py
- add flag to act as safe guard for dropping table (not in use yet)
- print meaningful error message
> better error message

- dataduct/utils/decorators.py
> Add more logging info in the timing decorator

- dataduct/utils/decorators.py
> Improve time delta message

- setup.py
> Fix the boto version

- dataduct/steps/reload.py
> Enforce by default

- dataduct/steps/executors/create_load_redshift.py
> Fix lint issues

- dataduct/s3/s3_file.py
- dataduct/steps/create_update_sql.py
- dataduct/steps/executors/runner.py
- dataduct/steps/upsert.py
@cliu587 @darinyu-coursera This should fix the 10000char limit issue.
> Sb fix 10000 char

- dataduct/database/parsers/transform.py
- dataduct/database/sql/tests/test_sql_statement.py
> Add more tests for 134

- dataduct/steps/etl_step.py
Fix typos with the worker group diff.
> emr -> emr_cluster, also make assert not spurious

- dataduct/steps/load_reload_pk.py
- dataduct/utils/constants.py
Fix a typo in `command` and correct argument propogation.
> Support for argument propogation
